### ISSUE TITLE
Drivers Intel 2ª Geração de Processadores Core.

### ISSUE THREAD

**Issue by Evertonlps** [Linux-BR/forum#10]
Atualmente estou em um PC de 2ª Geração i3, antes usava um AMD FX com Nvidia, e estou tendo dificuldades com Linux e acabo voltando ao  Windows, pois só assim pra jogar jogos que tenho no Steam, pois com Intel Graphics no Linux, pelo menos no meu velho i3 não está dando muito certo, não há o que eu faça pra ter bom FPS num CSGO, que no Windows e com esse processador e VGA consigo meu mínimo 60fps, eu preciso demais de alternativas, pois odeio a política do Windows, mas preciso do SO no momento para ter o máximo que esse hardware pode me dar, eu sou usuário Arch ou Mageia, as vezes usava OpenSuse, mas, quando tinha meu FX e Nvidia, com Intel i3 2ª Geração não estou satisfeito com Linux, e já deixo aqui meu sincero comentário sobre "Linux é melhor em hardware antigo", isso é mito do pessoal apaixonado e fan.
Enfim, o que eu posso fazer, que caminho tomar pra me livrar de Windows de vez? eu entendo bastante de Linux, fiz cursos e testei todas as distros "independentes" e  esse PC apesar do hardware ser de gerações passadas, comprei faz pouco tempo, novo  e veio com Mint, que não uso de forma alguma, não curto Ubuntu(s), nele nem cheguei a testar como seria o desempenho geral e com jogos Steam, formatei assim que chegou.

**Comment by jq2** [comment]
Olá, @Evertonlps , obrigado por postar seu problema aqui em nosso fórum. Mesmo que o fórum ainda não tenha muitos membros, o projeto será retomado, e tenho certeza que a participação de membros vai aumentar.

Quanto a frase "Linux é melhor em hardware antigo", quem disse isso, não sabe o que está dizendo, pois envolve versão do software e as especificações de hardware, ou seja, é algo muito relativo.

**Comment by Evertonlps** [comment]
> Olá, @Evertonlps , obrigado por postar seu problema aqui em nosso fórum. Mesmo que o fórum ainda não tenha muitos membros, o projeto será retomado, e tenho certeza que a participação de membros vai aumentar.
> 
> Quanto a frase "Linux é melhor em hardware antigo", quem disse isso, não sabe o que está dizendo, pois envolve versão do software e as especificações de hardware, ou seja, é algo muito relativo.

Ok, então não há mesmo uma solução pelo que entendi, tem que ter mais máquina mesmo. e na real, acho que nem assim resolve 100% já que a Steam em si já não está tão animada com Linux como no começo e provavelmente vão deixar de lado nos próximos anos, mas de qualquer forma pra outras coisas que não necessitem muito, ainda vou usar Linux, já que existem soluções Linux para reparar problemas Windows, firewall etc.
