### ISSUE TITLE
Vale a pena usar o arch linux ou é algo extremista demais ?

### ISSUE THREAD

**Issue by AlexandreUser** [linux-br/forum#2]
To pensando em mudar de distro, hoje em dia eu uso debian e fedora, tava querendo algo mais baixo nivel 
 ,mais simples , um amigo me recomendou o arch linux, porem vi um pessoal nos foruns falando que ele é bem complicado de usar. Enfim vale a pena ou não.

**Comment by jq2** [comment]
Olá, bem-vindo ao fórum!.

O modelo de lançamento do Arch Linux é o RR (Rolling Release), ou seja, os pacotes são lançados assim que são atualizados, permitindo que os usuários tenham sempre a versão mais recente do pacote/software em questão. Em contraste, isso causa vários problemas, já que o software é sempre atualizado para a versão mais recente.

As vantagens disso é que, uma vez que você adira ao conhecimento necessário para gerenciar uma distro RR, você será capaz de resolver problemas com muita facilidade. Com o tempo, essas tarefas se tornam algo prazeroso de resolver.


É possível instalar tanto pacotes binários quanto pacotes distribuídos em código-fonte (source-code).

Distribuições que considero low-level são distribuições baseadas em gerenciadores de pacotes baseados em código-fonte (mais conhecidas como source-based Linux distributions).

Usei Debian por vários anos, depois usei Arch Linux durante alguns anos, e recomendo!

Atualmente uso distribuições baseadas no LFS, construo minhas próprias distros para atender as minhas necessidades, .... porém, produtividade não é o meu objetivo, isso é um processo um tanto quanto chato de se produzir.

**Comment by cephalopodluke** [comment]
Short answer: vale.

 Entretanto, depende do quão familiarizado VC está com os sistemas Linux.

**Comment by AlexandreUser** [comment]
Eu comecei com linux no ubuntu 9.04, dali fui pro debian e nunca sai, obrigado pelas respostas, vou experimentar o Arch e posto minhas opiniões futuramente aqui.

**Comment by jq2** [comment]
Eu recomendo que você instale em uma máquina virtual e use por um tempo, pode ser sem interface gráfica mesmo.

**Comment by AlexandreUser** [comment]
> Eu recomendo que você instale em uma máquina virtual e use por um tempo, pode ser sem interface gráfica mesmo.
Obrigado pela dica, li mais sobre o arch linux e achei muito interessante, vou começar a usar ele aqui em um triple boot kkk.

**Comment by masterl** [comment]
Uma opção mais easy, caso vc ache o arch complicado é o Manjaro.
Utilizei o arch por um tempo, hj to usando o Manjaro e tem me atendido bem.
