### ISSUE TITLE
problemas com Winetricks

### ISSUE THREAD

**Issue by AlexandreUser** [linux-br/forum#6]
Atualmente meu wine tem funcionado muito bem, exceto quando preciso utilizar o winetricks, geralmente ele apresenta o seguinte erro:
error: dotnet45 conflicts with dotnet20, which is already installed.
Porem eu ja removi o dotnet20...

**Comment by cephalopodluke** [comment]
Já usou -q switch 

?

**Comment by jq2** [comment]
> Não tem nada relacionado a isso no github do winetricks

https://github.com/Winetricks/winetricks/issues/734#issuecomment-281763572

**Comment by jq2** [comment]
Manda a versão dos softwares (todos pacotes envolvidos)...
Qual sistema (uname -a/cat /etc/os-release) ?
Versão do wine/winetricks/dotnet/etc.

**Comment by AlexandreUser** [comment]
Reinstalei o Fedora e o winetricks e tudo voltou a funcionar
